#! /bin/bash
set -euf -o pipefail
D="$(dirname "$0")"

: ${CRF_V:=22}
. "$D/util.sh"

inf="$1"
program="$2"
shift 2
set +x
exec nice ffmpeg -copyts -thread_queue_size 99999 \
	-strict unofficial \
	-i "$inf" \
	-c copy \
	${CODEC_V_X264_YT[@]} \
	-map 0:p:"$program" \
	"$@"
