#! /bin/bash
set -euf -o pipefail

inf="$1"
shift
out_base="$1"
shift
start_seek="$1"
shift
to="$1"
shift

# nlmeans is very slow, hqdn3d is a fast alternative, but does not denoise as effectively.

#exec ffmpeg -i "$inf" -filter:v "bwdif,nlmeans,scale=1920:trunc(1920/dar/2)*2" \
#		-c:v libx264 -preset slow -profile:v high10 -crf 18 -coder 1 -pix_fmt yuv420p -movflags +faststart -g 30 -bf 2 \
#		-c:a aac -b:a 384k -profile:a aac_low "$@"

enc_v_flags="-c:v libx264 -preset slow -profile:v high10 -crf 18 -coder 1 -pix_fmt yuv420p -movflags +faststart -g 30 -bf 2"
enc_a_flags="-c:a aac -b:a 384k -profile:a aac_low"

exec nice ffmpeg -ss "$start_seek" -to "$to" -i "$inf" -filter_complex "\
	[0:v] bwdif [deint]; \
	[deint] split=2[deint0][deint1]; \
	[deint0] nlmeans [nl]; \
	[deint1] hqdn3d [hqdn]; \
	[nl] split=2[out_nl][nl1]; \
	[hqdn] split=2[out_hqdn][hqdn1]; \
	[hqdn1] scale=-2:1080[out_hqdn_1080p]; \
	[nl1] scale=-2:1080[out_nl_1080p]" \
	-max_muxing_queue_size 4000 \
	-map 0:a $enc_a_flags -map "[out_nl_1080p]"   $enc_v_flags "${out_base}"_nl_1080p.mp4 \
	-max_muxing_queue_size 4000 \
	-map 0:a $enc_a_flags -map "[out_hqdn_1080p]" $enc_v_flags "${out_base}"_hqdn3d_1080p.mp4 \
	-max_muxing_queue_size 4000 \
	-map 0:a $enc_a_flags -map "[out_hqdn]"       $enc_v_flags "${out_base}"_hqdn3d.mp4 \
	-max_muxing_queue_size 4000 \
	-map 0:a $enc_a_flags -map "[out_nl]"         $enc_v_flags "${out_base}"_nl.mp4
