#! /bin/bash
D="$(dirname "$0")"
. "$D"/util.sh

file=$1
start=$2
end=$3
if [ $# -eq 3 ]; then
	out_base=$(basename $1 .mkv)
else
	out_base=$4
fi

nice ffmpeg -ss "$start" -to "$end" -i "$file" \
	-filter:v bwdif,nlmeans \
	${CODEC_V_FFV1[@]} \
	-c:a copy \
	"$out_base".yt1.tmp1.mkv

exec nice ffmpeg -i "$out_base".tmp1.mkv \
	${CODEC_V_X264_YT[@]} \	
	${CODEC_A_AAC_YT[@]} \
	"$out_base".yt1.mp4
