#! /bin/bash
set -euf -o pipefail
set -x
D="$(dirname "$0")"
. "$D"/util.sh

N="$(basename "$0")"

if [ $# -lt 4 ]; then
	>& echo "usage: $0 <file> <start-ts> <end-ts> <crop-spec> [<out_base>]"
	exit 1
fi

file="$1"
start="$2"
end="$3"
crop="$4"
if [ $# -eq 4 ]; then
	out_base="$PWD/$(basename "$file" .mkv)"
else
	out_base=$5
fi

echo "file: $file"
echo "start: $start"
echo "end: $end"
echo "out_base: $out_base"
echo "N: $N"

: ${codec_v:="${CODEC_V_X264_YT[@]}"}
: ${codec_a:="${CODEC_A_AAC_YT[@]}"}

echo "codec_v: $codec_v"
echo "codec_a: $codec_a"

exec nice ffmpeg -nostdin -ss "$start" -to "$end" \
	-i "$file" \
	-filter:v 'bwdif,crop='"$crop"',nlmeans,scale=trunc(1080*dar/2)*2:1080:flags=lanczos' \
	${codec_v[@]} \
	${codec_a[@]} \
	"$out_base"."$start"."$end"."$crop"."$N"."$PRESET_V"."$CRF_V".mp4
