#! /bin/bash
# yt3, but cover the bottom N pixels with black

set -euf -o pipefail
set -x
D="$(dirname "$0")"
. "$D"/util.sh

N="$(basename "$0")"

if [ $# -eq 0 ]; then
	>&2 echo "usage: $0 <input_file> <start_ts> <end_ts> <bottom_pixels_cover> [<out_base>]"
	exit 1
fi

file=$1
start=$2
end=$3
bottom_pixel_cover=$4
if [ $# -eq 4 ]; then
	out_base="$(basename "$file" .mkv)"
else
	out_base=$5
fi

echo "file: $file"
echo "start: $start"
echo "end: $end"
echo "out_base: $out_base"
echo "N: $N"

: ${codec_v:="${CODEC_V_X264_YT[@]}"}
: ${codec_a:="${CODEC_A_AAC_YT[@]}"}

echo "codec_v: $codec_v"
echo "codec_a: $codec_a"

# WARNING: we assume width & height of video matches NTSC
exec nice ffmpeg -ss "$start" -to "$end" \
	-i "$file" \
	-filter:v "nlmeans,bwdif,drawbox=c=black:x=0:y=$((480-bottom_pixel_cover)):h=$bottom_pixel_cover:w=720:t=fill,scale=1080*dar:1080:flags=lanczos" \
	${codec_v[@]} \
	${codec_a[@]} \
	"$out_base"."$N"_"$PRESET_V"_"$CRF_V"_"$start"_"$end".mp4
