#! /bin/sh

shapath=$HOME/.boot.sha512

update() {
	sha512sum /boot/vm* > $shapath
}

check() {
	if ! sha512sum /boot/vm* | cmp $shapath /dev/stdin; then
		echo "OMG. DIFFERENT."
	else
		echo "Good to go."
	fi
}

usage() {
	echo "$0 <check|update>"
	exit 1
}

if [ $# -ne 1 ] ; then
	usage
fi

case $1 in
check)
	check
	;;

update)
	update
	;;

*)
	usage
	;;

esac

