#LINUX_OVERRIDE_SRCDIR = $(HOME)/g/linux
#DNUMA_OVERRIDE_SRCDIR = $(HOME)/trifles
#GCC_OVERRIDE_SRCDIR   = $(HOME)/g/gcc
#BINUTILS_OVERRIDE_SRCDIR = $(HOME)/g/binutils
TINIA_OVERRIDE_SRCDIR  = $(HOME)/g/tinia
