[workspace]
members = [
	"arm-bits",
	"gopro-util",
	"helloworld-capn",
	"helloworld-tonic",
	"holdoff",
	"mac",
	"lk",
	"iflet2",
	"onlyn",
	"test-fetch",
	"udp-spam",
	"replace",
	"zbus-systemd-start",
]
