#! /bin/sh
set -euf -o pipefail

if [ $# -eq 1 ]; then
	OUT="$1"
else
	echo "usage: $(basename $0) [base-dir-of-initramfs]"
	exit 1
fi

: ${STEPPING:=$(grep 'stepping[[:space:]]*:' /proc/cpuinfo | tail -n 1 | cut -f2 -d: )}
: ${FAMILY:=$(grep 'cpu family[[:space:]]*:' /proc/cpuinfo | tail -n 1 | cut -f2 -d: )}
: ${MODEL:=$(grep 'model[[:space:]]*:' /proc/cpuinfo | tail -n 1 | cut -f2 -d: )}

n=$(printf "%02x-%02x-%02x\n" "$FAMILY" "$MODEL" "$STEPPING")
if [ -n "$DEBUG" ]; then
	echo "Detected: fam-mod-step = $n"
fi

src="/lib/firmware/intel-ucode/$n"
if ! [ -e "$src" ]; then
	echo "No intel-ucode for your processor exists ($n)"
	exit 0
fi

p="$OUT"/kernel/x86/microcode
pf="$p"/GenuineIntel.bin
mkdir -p -- "$p"
cp "$src" "$pf"
