#! /bin/sh
set -eu -o pipefail

DEST_DIR="$1"
shift

for SRC_DIR in "$@"; do
	D="$DEST_DIR/$(basename "$SRC_DIR")"
	if ! [ -d "$DEST_DIR" ]; then
		>&2 echo "DEST_DIR='$DEST_DIR' does not exist"
		exit 1
	fi	

	for f in "$SRC_DIR"/*.flac; do

		mkdir -p "$D"
		R="$D/$(basename "$f" .flac | iconv -f UTF-8 -t ASCII//TRANSLIT).m4a"
		if [ -e "$R" ]; then
			rm "$R"
		fi

		ffmpeg -i "$f" -c:a libfdk_aac -cutoff 18000 -b:a 192k -ar 44100 -ac 2 -vn "$R"
	done
done
