#! /bin/bash
set -x
set -euf -o pipefail

PIA_HOME=/etc/pia
. "$PIA_HOME"/account

PIA_TOKEN="$(curl -s -u "$PIA_USERNAME:$PIA_PASSWORD" \
	"https://privateinternetaccess.com/gtoken/generateToken" | jq -r '.token')"

pia_servers="$(curl --max-time 15 'https://serverlist.piaservers.net/vpninfo/servers/v6' | head -1)"

# remote ips
country_json="$(printf "%s" "$pia_servers" | jq '.regions[] | select (.country == "NO")')"
#WG_HOSTNAME=$(printf "%s" "$country_json" | jq -r .dns)


servers_json="$(printf "%s" "$country_json" | jq '.servers.wg')"
server_json="$(printf "%s" "$servers_json" | jq '.[0]')"
# ports

WG_PRIVKEY="$(wg genkey)"
WG_PUBKEY="$(printf "%s" "$WG_PRIVKEY" | wg pubkey)"

WG_SERVER_IP=$(printf "%s" "$server_json" | jq -r .ip)
WG_HOSTNAME=$(printf "%s" "$server_json" | jq -r .cn)

wireguard_json="$(curl -vv -G \
  --connect-to "$WG_HOSTNAME::$WG_SERVER_IP:" \
  --cacert "$PIA_HOME/ca.rsa.4096.crt" \
  --data-urlencode "pt=${PIA_TOKEN}" \
  --data-urlencode "pubkey=$WG_PUBKEY" \
  "https://${WG_HOSTNAME}:1337/addKey" )"

if [ "$(echo "$wireguard_json" | jq -r '.status')" != "OK" ];then
	echo "addKey failed: $wireguard_json"
	exit 1
fi

#mkdir -p /run/pia/
#touch /run/pia/pia.key
#chmod 0640 /run/pia/pia.key
#chown root:systemd-network /run/pia/pia.key
#echo "$WG_PRIVKEY" >/run/pia/pia.key

WG_ADDR="$(echo "$wireguard_json" | jq -r .peer_ip)"
WG_SERVER_PUBKEY="$(echo "$wireguard_json" | jq -r .server_key)"
WG_SERVER_PORT="$(echo "$wireguard_json" | jq -r .server_port)"
WG_SERVER_ENDPOINT="$WG_SERVER_IP:$WG_SERVER_PORT"

WG_SERVER_DNS="$(echo "$wireguard_json" | jq -r '.dns_servers[0]')"

cat <<EOF
# 10-pia.netdev
[NetDev]
Name = pia
Kind = wireguard

[WireGuard]
PrivateKey = $WG_PRIVKEY

[WireGuardPeer]
PublicKey = $WG_SERVER_PUBKEY
AllowedIPs = 0.0.0.0/0
Endpoint = $WG_SERVER_ENDPOINT
PersistentKeepalive = 25

EOF
cat <<EOF
# 10-pia.network

[Match]
Name=pia

[Network]
Address = $WG_ADDR
DNSSEC = false

# FIXME: use array?
DNS = $WG_SERVER_DNS
EOF

cat <<EOF
# wg-quick
[Interface]
Address = $WG_ADDR
PrivateKey = $WG_PRIVKEY

[Peer]
PersistentKeepalive = 25
PublicKey = $WG_SERVER_PUBKEY
AllowedIPs = 0.0.0.0/0
Endpoint = $WG_SERVER_ENDPOINT
EOF
