#! /bin/sh

set -euf -o pipefail

: ${CROSS_COMPILE:=}
: ${CC:=${CROSS_COMPILE}gcc}
: ${AR:=${CROSS_COMPILE}ar}
: ${CFLAGS=-Wall -Wextra -O2 -ggdb3 -fsanitize=undefined -Wl,--as-needed}

CFLAGS_NO_UBSAN=${CFLAGS/-fsanitize=undefined/}

: ${NEED_SYS:=false}

set -x

${CC} ${CFLAGS_NO_UBSAN} -c -o ubsan_simple.o ubsan_simple.c
#rm -f libubsan.a
${AR} rcDs libubsan.a ubsan_simple.o

${CC} ${CFLAGS} -c -o test.o test.c
if ${NEED_SYS}; then
	${CC} ${CFLAGS} -c -o sys.o sys.c
fi

if ${NEED_SYS}; then
	EXTRA_OBJ=sys.o
else
	EXTRA_OBJ=
fi

${CC} ${CFLAGS} -L . -o test test.o ${EXTRA_OBJ}
