[package]
name = "nib"
description = "Nibble references and slices"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
edition = "2018"
license = "GPL-3.0-or-later WITH GCC-exception-2.0"

[dependencies]
